[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
load_image = "2.16.4"
png = "0.17.5"
rand = { version = "0.8.5", features = ["small_rng"] }
